# =============================================================================
# gpio_exclusions.tcl - coverage waivers for block 19, the GPIO.
#
# Applied in IMC after loading the merged GPIO run:
#     imc -exec flow/cov/gpio_report.tcl
# or typed at the IMC prompt. Every line has its reason. Sign-off criterion 3
# (flow/0_signoff_criteria.md): code coverage 100% after the waivers below.
#
# Five reasons cover everything here:
#   1. No register of this block is wider than 8 bits, and ID is the constant
#      0x6A5D_1301: the read-data bits listed are 0 in every register (GPIO
#      section 6). Checked on every read by the scoreboard.
#   2. PREADY is tied high (AHB2APB 7.5); checked by a_shim_pready. The
#      vendored block's own PSLVERR is tied low and left unconnected: the shim
#      makes PSLVERR.
#   3. The GPIO has no DMA channel (GPIO [N-13.2]): the shim's DMA inputs are
#      tied off in garuda_gpio_top. That logic is exercised in the blocks that
#      use it (UART, I2C, SPI). a_no_dma_req checks that no request ever leaves.
#   4. The vendored register file is written for 64 pins and built here with
#      PAD_NUM = 2. Logic of a pin that does not exist is dead by parameter:
#      the clock enables of pins 2 to 63, and the branches "if (i < PAD_NUM)"
#      inside loops that run over pins 8 and above.
#   5. dft_cg_enable_i is tied low until scan insertion (GPIO [N-9.3], OPEN-G1).
# =============================================================================
exclude -inst garuda_gpio_top -toggle prdata_o\[31\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[31\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[28\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[28\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[26\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[26\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[24\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[24\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[23\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[23\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[21\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[21\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[17\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[17\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[15\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[15\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[14\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[14\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[13\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[13\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[11\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[11\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle prdata_o\[10\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle prdata_o\[10\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[8\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[8\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[8\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[9\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[9\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[9\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[10\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[10\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[10\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[11\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[11\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[11\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[12\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[12\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[12\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[13\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[13\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[13\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[14\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[14\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[14\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[15\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[15\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[15\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[16\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[16\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[16\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[17\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[17\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[17\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[18\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[18\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[18\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[19\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[19\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[19\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[20\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[20\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[20\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[21\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[21\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[21\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[22\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[22\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[22\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[23\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[23\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[23\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[24\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[24\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[24\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[25\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[25\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[25\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[26\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[26\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[26\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[27\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[27\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[27\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[28\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[28\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[28\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[29\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[29\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[29\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[30\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[30\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[30\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle ip_prdata\[31\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_shim -toggle ip_prdata_i\[31\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top.u_gpio -toggle PRDATA\[31\] -comment "read-data bit that is 0 in every register of this block: constant by specification, checked by the scoreboard on every read"
exclude -inst garuda_gpio_top -toggle pready_o -comment "PREADY is tied high, no wait states: checked by a_shim_pready and sb_pready"
exclude -inst garuda_gpio_top -toggle ip_pready -comment "PREADY is tied high, no wait states: checked by a_shim_pready and sb_pready"
exclude -inst garuda_gpio_top.u_shim -toggle pready_o -comment "PREADY is tied high, no wait states: checked by a_shim_pready and sb_pready"
exclude -inst garuda_gpio_top.u_shim -toggle ip_pready_i -comment "PREADY is tied high, no wait states: checked by a_shim_pready and sb_pready"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -toggle pready_o -comment "PREADY is tied high, no wait states: checked by a_shim_pready and sb_pready"
exclude -inst garuda_gpio_top.u_gpio -toggle PREADY -comment "PREADY is tied high, no wait states: checked by a_shim_pready and sb_pready"
exclude -inst garuda_gpio_top.u_gpio -toggle PSLVERR -comment "tied low in the vendored block and left unconnected: the shim makes PSLVERR"
exclude -inst garuda_gpio_top.u_shim -toggle rx_avail_i -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim -toggle tx_space_i -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim -toggle dma_ack_i -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim -toggle dma_req_o -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim -toggle holdoff_q -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -toggle rx_avail_i -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -toggle tx_space_i -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -toggle dma_ack_i -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -toggle dma_req_o -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_gpio_sva -toggle dma_req -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -assertion a_shim_dma_holdoff -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_shim.u_shim_sva -assertion a_shim_dma_gate -comment "tied off in garuda_gpio_top: the GPIO has no DMA channel; covered in the blocks that use the shim's DMA logic"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[2\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[3\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[4\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[5\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[6\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[7\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[8\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[9\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[10\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[11\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[12\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[13\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[14\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[15\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[16\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[17\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[18\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[19\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[20\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[21\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[22\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[23\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[24\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[25\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[26\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[27\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[28\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[29\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[30\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[31\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[32\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[33\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[34\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[35\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[36\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[37\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[38\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[39\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[40\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[41\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[42\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[43\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[44\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[45\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[46\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[47\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[48\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[49\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[50\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[51\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[52\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[53\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[54\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[55\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[56\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[57\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[58\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[59\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[60\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[61\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[62\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_cg_en\[63\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[1\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[2\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[3\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[4\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[5\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[6\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[7\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[8\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[9\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[10\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[11\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[12\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[13\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[14\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle s_clk_en\[15\] -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 18 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 83 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 93 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 123 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 133 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 143 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 153 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 163 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 168 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 173 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 183 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 193 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 203 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 208 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 213 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 218 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 223 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 228 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -block 233 -comment "logic of a pin that does not exist: the vendored block is written for 64 pins and built with PAD_NUM = 2"
exclude -inst garuda_gpio_top.u_gpio -toggle dft_cg_enable_i -comment "tied low until scan insertion: GPIO spec N-9.3, open item OPEN-G1"
exclude -inst garuda_gpio_top.u_shim -block 27 -comment "the shim's report that an IP held PREADY low: the vendored GPIO ties PREADY high, so the report can never print here"
exclude -inst garuda_gpio_top.u_shim -expression 4.1 -comment "condition of the same report: ip_pready_i is tied high by the vendored GPIO"
