# =============================================================================
# timers_exclusions.tcl - coverage waivers for block 11, timers and watchdog.
#
# Applied in IMC after loading the merged timers run:
#     imc -exec flow/cov/timers_report.tcl
# or typed at the IMC prompt. Every line has its reason. Sign-off criterion 3
# (flow/0_signoff_criteria.md): code coverage 100% after the waivers below.
#
# Two reasons cover everything here:
#   WDTCTL bits 31:2 are reserved and read 0 (TIMERS section 6, WDTCTL); the
#   32-bit read bus for that register carries 30 constant zeros. Checked on
#   every WDTCTL read by the scoreboard and by the register bit-bash test.
#   PREADY is tied high: the block never inserts a wait state (TIMERS
#   [N-7.11]); checked by property a_pready and scoreboard check sb_pready.
# =============================================================================
exclude -inst timers_top -toggle ctl\[2\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[3\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[4\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[5\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[6\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[7\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[8\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[9\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[10\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[11\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[12\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[13\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[14\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[15\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[16\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[17\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[18\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[19\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[20\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[21\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[22\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[23\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[24\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[25\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[26\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[27\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[28\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[29\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[30\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle ctl\[31\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[2\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[3\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[4\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[5\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[6\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[7\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[8\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[9\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[10\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[11\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[12\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[13\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[14\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[15\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[16\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[17\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[18\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[19\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[20\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[21\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[22\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[23\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[24\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[25\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[26\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[27\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[28\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[29\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[30\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_apb -toggle wdtctl_i\[31\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[2\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[3\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[4\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[5\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[6\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[7\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[8\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[9\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[10\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[11\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[12\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[13\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[14\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[15\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[16\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[17\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[18\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[19\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[20\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[21\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[22\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[23\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[24\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[25\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[26\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[27\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[28\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[29\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[30\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top.u_wdt -toggle ctl_o\[31\] -comment "reserved bit of WDTCTL, reads 0: constant by specification, checked by the scoreboard on every WDTCTL read"
exclude -inst timers_top -toggle pready_o -comment "PREADY is tied high, no wait states: checked by a_pready and sb_pready"
exclude -inst timers_top.u_apb -toggle pready_o -comment "PREADY is tied high, no wait states: checked by a_pready and sb_pready"
exclude -inst timers_top.u_timers_sva -toggle pready_o -comment "PREADY is tied high, no wait states: checked by a_pready and sb_pready"
