
// This file was autogenerated by PeakRDL-uvm
package pwm_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - pwm::PRESCALE
    class pwm__PRESCALE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pwm__PRESCALE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__PRESCALE

    // Reg - pwm::PERIOD
    class pwm__PERIOD extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pwm__PERIOD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__PERIOD

    // Reg - pwm::CTRL
    class pwm__CTRL extends uvm_reg;
        rand uvm_reg_field en;
        rand uvm_reg_field ch_en;

        function new(string name = "pwm__CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.ch_en = new("ch_en");
            this.ch_en.configure(this, 4, 4, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__CTRL

    // Reg - pwm::STATUS
    class pwm__STATUS extends uvm_reg;
        rand uvm_reg_field count;
        rand uvm_reg_field clamp;

        function new(string name = "pwm__STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.count = new("count");
            this.count.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
            this.clamp = new("clamp");
            this.clamp.configure(this, 4, 16, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : pwm__STATUS

    // Reg - pwm::DUTY
    class pwm__DUTY extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pwm__DUTY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__DUTY

    // Reg - pwm::IRQSTAT
    class pwm__IRQSTAT extends uvm_reg;
        rand uvm_reg_field boundary;
        rand uvm_reg_field clamped;

        function new(string name = "pwm__IRQSTAT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.boundary = new("boundary");
            this.boundary.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.clamped = new("clamped");
            this.clamped.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__IRQSTAT

    // Reg - pwm::IRQEN
    class pwm__IRQEN extends uvm_reg;
        rand uvm_reg_field en;

        function new(string name = "pwm__IRQEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__IRQEN

    // Reg - pwm::DMACTL
    class pwm__DMACTL extends uvm_reg;
        rand uvm_reg_field req;

        function new(string name = "pwm__DMACTL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.req = new("req");
            this.req.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pwm__DMACTL

    // Reg - pwm::ID
    class pwm__ID extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "pwm__ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 0, 'h6a5d1401, 1, 1, 0);
        endfunction : build
    endclass : pwm__ID

    // Addrmap - pwm
    class pwm extends uvm_reg_block;
        rand pwm__PRESCALE PRESCALE;
        rand pwm__PERIOD PERIOD;
        rand pwm__CTRL CTRL;
        rand pwm__STATUS STATUS;
        rand pwm__DUTY DUTY[4];
        rand pwm__IRQSTAT IRQSTAT;
        rand pwm__IRQEN IRQEN;
        rand pwm__DMACTL DMACTL;
        rand pwm__ID ID;

        function new(string name = "pwm");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.PRESCALE = new("PRESCALE");
            this.PRESCALE.configure(this);

            this.PRESCALE.build();
            this.default_map.add_reg(this.PRESCALE, 'h0);
            this.PERIOD = new("PERIOD");
            this.PERIOD.configure(this);

            this.PERIOD.build();
            this.default_map.add_reg(this.PERIOD, 'h4);
            this.CTRL = new("CTRL");
            this.CTRL.configure(this);

            this.CTRL.build();
            this.default_map.add_reg(this.CTRL, 'h8);
            this.STATUS = new("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'hc);
            foreach(this.DUTY[i0]) begin
                this.DUTY[i0] = new($sformatf("DUTY[%0d]", i0));
                this.DUTY[i0].configure(this);
                
                this.DUTY[i0].build();
                this.default_map.add_reg(this.DUTY[i0], 'h10 + i0*'h4);
            end
            this.IRQSTAT = new("IRQSTAT");
            this.IRQSTAT.configure(this);

            this.IRQSTAT.build();
            this.default_map.add_reg(this.IRQSTAT, 'hfe0);
            this.IRQEN = new("IRQEN");
            this.IRQEN.configure(this);

            this.IRQEN.build();
            this.default_map.add_reg(this.IRQEN, 'hfe4);
            this.DMACTL = new("DMACTL");
            this.DMACTL.configure(this);

            this.DMACTL.build();
            this.default_map.add_reg(this.DMACTL, 'hfe8);
            this.ID = new("ID");
            this.ID.configure(this);

            this.ID.build();
            this.default_map.add_reg(this.ID, 'hfec);
        endfunction : build
    endclass : pwm

endpackage: pwm_reg_pkg
