
// This file was autogenerated by PeakRDL-uvm
package clic_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - clic::CLICINFO
    class clic__CLICINFO extends uvm_reg;
        rand uvm_reg_field num_interrupt;
        rand uvm_reg_field version;
        rand uvm_reg_field ctlbits;
        rand uvm_reg_field rsvd;

        function new(string name = "clic__CLICINFO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.num_interrupt = new("num_interrupt");
            this.num_interrupt.configure(this, 13, 0, "RO", 0, 'h20, 1, 1, 0);
            this.version = new("version");
            this.version.configure(this, 8, 13, "RO", 0, 'h1, 1, 1, 0);
            this.ctlbits = new("ctlbits");
            this.ctlbits.configure(this, 4, 21, "RO", 0, 'h8, 1, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 7, 25, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : clic__CLICINFO

    // Reg - clic::CLICIE
    class clic__CLICIE extends uvm_reg;
        rand uvm_reg_field id0;
        rand uvm_reg_field dma_complete;
        rand uvm_reg_field id7;
        rand uvm_reg_field dma_error;
        rand uvm_reg_field periph;
        rand uvm_reg_field unassigned;

        function new(string name = "clic__CLICIE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.id0 = new("id0");
            this.id0.configure(this, 1, 0, "RO", 0, 'h0, 1, 1, 0);
            this.dma_complete = new("dma_complete");
            this.dma_complete.configure(this, 6, 1, "RW", 0, 'h0, 1, 1, 0);
            this.id7 = new("id7");
            this.id7.configure(this, 1, 7, "RO", 0, 'h0, 1, 1, 0);
            this.dma_error = new("dma_error");
            this.dma_error.configure(this, 6, 8, "RW", 0, 'h0, 1, 1, 0);
            this.periph = new("periph");
            this.periph.configure(this, 9, 14, "RW", 0, 'h0, 1, 1, 0);
            this.unassigned = new("unassigned");
            this.unassigned.configure(this, 9, 23, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : clic__CLICIE

    // Reg - clic::CLICIP
    class clic__CLICIP extends uvm_reg;
        rand uvm_reg_field pending;

        function new(string name = "clic__CLICIP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.pending = new("pending");
            this.pending.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : clic__CLICIP

    // Reg - clic::CLICINTCFG
    class clic__CLICINTCFG extends uvm_reg;
        rand uvm_reg_field lvl;
        rand uvm_reg_field rsvd;

        function new(string name = "clic__CLICINTCFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.lvl = new("lvl");
            this.lvl.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : clic__CLICINTCFG

    // Addrmap - clic
    class clic extends uvm_reg_block;
        rand clic__CLICINFO CLICINFO;
        rand clic__CLICIE CLICIE;
        rand clic__CLICIP CLICIP;
        rand clic__CLICINTCFG CLICINTCFG[32];

        function new(string name = "clic");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.CLICINFO = new("CLICINFO");
            this.CLICINFO.configure(this);

            this.CLICINFO.build();
            this.default_map.add_reg(this.CLICINFO, 'h0);
            this.CLICIE = new("CLICIE");
            this.CLICIE.configure(this);

            this.CLICIE.build();
            this.default_map.add_reg(this.CLICIE, 'h4);
            this.CLICIP = new("CLICIP");
            this.CLICIP.configure(this);

            this.CLICIP.build();
            this.default_map.add_reg(this.CLICIP, 'h8);
            foreach(this.CLICINTCFG[i0]) begin
                this.CLICINTCFG[i0] = new($sformatf("CLICINTCFG[%0d]", i0));
                this.CLICINTCFG[i0].configure(this);
                
                this.CLICINTCFG[i0].build();
                this.default_map.add_reg(this.CLICINTCFG[i0], 'h100 + i0*'h4);
            end
        endfunction : build
    endclass : clic

endpackage: clic_reg_pkg
