// GENERATED by tools/garuda_gen.py from Design_Docs/garuda_system.yaml - DO NOT EDIT
`ifndef GARUDA_MAP_VH
`define GARUDA_MAP_VH

// ---- Identity ----
`define GARUDA_SYS_REVISION                 "4.0"  // GARUDA-SYS-001
// ---- Clocks ----
`define GARUDA_REFCLK_MHZ                   500  // external reference
`define GARUDA_HCLK_MHZ                     250  // refclk / DIV (default)
`define GARUDA_HCLK_DIV_DEFAULT             2  // divider encoding is 2/4/8/16
`define GARUDA_PCLK_MHZ                     125  // hclk / 2, toggle flop
// ---- Reset ----
`define GARUDA_RESET_STRETCH_CYCLES         1024  // refclk cycles
// ---- Address map ----
`define GARUDA_ISRAM_BASE                   32'h0000_0000
`define GARUDA_ISRAM_SIZE                   32'h0001_0000  // 64 KiB
`define GARUDA_BOOTROM_BASE                 32'h1000_0000
`define GARUDA_BOOTROM_SIZE                 32'h0000_1000  // 4 KiB
`define GARUDA_DSRAM_BASE                   32'h2000_0000
`define GARUDA_DSRAM_SIZE                   32'h0001_0000  // 64 KiB
`define GARUDA_APB_BASE                     32'h4000_0000
`define GARUDA_APB_SIZE                     32'h0000_C000  // 48 KiB
// ---- APB ----
`define GARUDA_APB_WINDOW_BYTES             32'h0000_1000
`define GARUDA_APB_TIMEOUT_PCLK             16  // PREADY timeout
`define GARUDA_APB_WIN_SPI_MASTER           1  // 0x40001000, block 13
`define GARUDA_APB_BASE_SPI_MASTER          32'h4000_1000
`define GARUDA_APB_WIN_I2C                  2  // 0x40002000, block 15
`define GARUDA_APB_BASE_I2C                 32'h4000_2000
`define GARUDA_APB_WIN_UART0                3  // 0x40003000, block 16
`define GARUDA_APB_BASE_UART0               32'h4000_3000
`define GARUDA_APB_WIN_UART1                4  // 0x40004000, block 17
`define GARUDA_APB_BASE_UART1               32'h4000_4000
`define GARUDA_APB_WIN_DMA_CFG              5  // 0x40005000, block 9
`define GARUDA_APB_BASE_DMA_CFG             32'h4000_5000
`define GARUDA_APB_WIN_UART2                6  // 0x40006000, block 18
`define GARUDA_APB_BASE_UART2               32'h4000_6000
`define GARUDA_APB_WIN_GPIO                 7  // 0x40007000, block 19
`define GARUDA_APB_BASE_GPIO                32'h4000_7000
`define GARUDA_APB_WIN_PWM                  8  // 0x40008000, block 20
`define GARUDA_APB_BASE_PWM                 32'h4000_8000
`define GARUDA_APB_WIN_RESET_CTRL           9  // 0x40009000, block 22
`define GARUDA_APB_BASE_RESET_CTRL          32'h4000_9000
`define GARUDA_APB_WIN_CLIC_CFG             10  // 0x4000A000, block 10
`define GARUDA_APB_BASE_CLIC_CFG            32'h4000_A000
`define GARUDA_APB_WIN_TIMERS_CFG           11  // 0x4000B000, block 11
`define GARUDA_APB_BASE_TIMERS_CFG          32'h4000_B000
`define GARUDA_APB_WINDOW_MASK_ALL          32'h0000_0FFE  // every window the map defines
// ---- CLIC IDs ----
`define GARUDA_CLIC_ID_DMA_COMPLETE_CH0_5_FIRST 1  // 1..6
`define GARUDA_CLIC_ID_DMA_ERROR_CH0_5_FIRST 7  // 7..12
`define GARUDA_CLIC_ID_SPI_MASTER           15
`define GARUDA_CLIC_ID_I2C                  16
`define GARUDA_CLIC_ID_UART0                17
`define GARUDA_CLIC_ID_UART1                18
`define GARUDA_CLIC_ID_UART2                19
`define GARUDA_CLIC_ID_GPIO_AGGREGATE       20
`define GARUDA_CLIC_ID_PWM_FAULT            21
`define GARUDA_CLIC_ID_WDT_EARLY_WARNING    22
`define GARUDA_CLIC_NUM_IDS                 32
// ---- DMA ----
`define GARUDA_DMA_CHANNELS                 6
`define GARUDA_DMA_PRIO_CH0                 5  // spi_master
`define GARUDA_DMA_PRIO_CH1                 3  // i2c
`define GARUDA_DMA_PRIO_CH2                 1  // uart0
`define GARUDA_DMA_PRIO_CH3                 2  // uart1
`define GARUDA_DMA_PRIO_CH4                 4  // reserved
`define GARUDA_DMA_PRIO_CH5                 0  // uart2
`define GARUDA_DMA_CH_SPI_MASTER            0  // IMU
`define GARUDA_DMA_CH_I2C                   1  // baro_mag_sonar
`define GARUDA_DMA_CH_UART0                 2  // GPS
`define GARUDA_DMA_CH_UART1                 3  // ground_link
`define GARUDA_DMA_CH_UART2                 5  // console
// ---- Boot ----
`define GARUDA_RESET_VECTOR                 32'h1000_0000

`endif
