
// This file was autogenerated by PeakRDL-uvm
package crg_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - crg::RSTREASON
    class crg__RSTREASON extends uvm_reg;
        rand uvm_reg_field ext;
        rand uvm_reg_field wdt;
        rand uvm_reg_field ndm;
        rand uvm_reg_field swr;
        rand uvm_reg_field bootfail;

        function new(string name = "crg__RSTREASON");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ext = new("ext");
            this.ext.configure(this, 1, 0, "W1C", 1, 'h1, 1, 1, 0);
            this.wdt = new("wdt");
            this.wdt.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.ndm = new("ndm");
            this.ndm.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.swr = new("swr");
            this.swr.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            this.bootfail = new("bootfail");
            this.bootfail.configure(this, 1, 4, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : crg__RSTREASON

    // Reg - crg::RSTCTL
    class crg__RSTCTL extends uvm_reg;
        rand uvm_reg_field swrst;
        rand uvm_reg_field bootfail_set;
        rand uvm_reg_field divsel;

        function new(string name = "crg__RSTCTL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.swrst = new("swrst");
            this.swrst.configure(this, 1, 0, "WO", 0, 'h0, 0, 1, 0);
            this.bootfail_set = new("bootfail_set");
            this.bootfail_set.configure(this, 1, 4, "WO", 0, 'h0, 0, 1, 0);
            this.divsel = new("divsel");
            this.divsel.configure(this, 2, 8, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : crg__RSTCTL

    // Reg - crg::CLKSTAT
    class crg__CLKSTAT extends uvm_reg;
        rand uvm_reg_field divact;
        rand uvm_reg_field divbusy;
        rand uvm_reg_field bootsel;

        function new(string name = "crg__CLKSTAT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.divact = new("divact");
            this.divact.configure(this, 2, 0, "RO", 1, 'h0, 0, 1, 0);
            this.divbusy = new("divbusy");
            this.divbusy.configure(this, 1, 2, "RO", 1, 'h0, 0, 1, 0);
            this.bootsel = new("bootsel");
            this.bootsel.configure(this, 1, 8, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : crg__CLKSTAT

    // Reg - crg::MEMCTL
    class crg__MEMCTL extends uvm_reg;
        rand uvm_reg_field ilock;

        function new(string name = "crg__MEMCTL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ilock = new("ilock");
            this.ilock.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : crg__MEMCTL

    // Addrmap - crg
    class crg extends uvm_reg_block;
        rand crg__RSTREASON RSTREASON;
        rand crg__RSTCTL RSTCTL;
        rand crg__CLKSTAT CLKSTAT;
        rand crg__MEMCTL MEMCTL;

        function new(string name = "crg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.RSTREASON = new("RSTREASON");
            this.RSTREASON.configure(this);

            this.RSTREASON.build();
            this.default_map.add_reg(this.RSTREASON, 'h0);
            this.RSTCTL = new("RSTCTL");
            this.RSTCTL.configure(this);

            this.RSTCTL.build();
            this.default_map.add_reg(this.RSTCTL, 'h4);
            this.CLKSTAT = new("CLKSTAT");
            this.CLKSTAT.configure(this);

            this.CLKSTAT.build();
            this.default_map.add_reg(this.CLKSTAT, 'h8);
            this.MEMCTL = new("MEMCTL");
            this.MEMCTL.configure(this);

            this.MEMCTL.build();
            this.default_map.add_reg(this.MEMCTL, 'h20);
        endfunction : build
    endclass : crg

endpackage: crg_reg_pkg
