
// This file was autogenerated by PeakRDL-uvm
package gpio_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - gpio::PADDIR
    class gpio__PADDIR extends uvm_reg;
        rand uvm_reg_field dir;

        function new(string name = "gpio__PADDIR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dir = new("dir");
            this.dir.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__PADDIR

    // Reg - gpio::GPIOEN
    class gpio__GPIOEN extends uvm_reg;
        rand uvm_reg_field en;

        function new(string name = "gpio__GPIOEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__GPIOEN

    // Reg - gpio::PADIN
    class gpio__PADIN extends uvm_reg;
        rand uvm_reg_field pin;

        function new(string name = "gpio__PADIN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.pin = new("pin");
            this.pin.configure(this, 2, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : gpio__PADIN

    // Reg - gpio::PADOUT
    class gpio__PADOUT extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio__PADOUT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__PADOUT

    // Reg - gpio::PADOUTSET
    class gpio__PADOUTSET extends uvm_reg;
        rand uvm_reg_field set;

        function new(string name = "gpio__PADOUTSET");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.set = new("set");
            this.set.configure(this, 2, 0, "WO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : gpio__PADOUTSET

    // Reg - gpio::PADOUTCLR
    class gpio__PADOUTCLR extends uvm_reg;
        rand uvm_reg_field clr;

        function new(string name = "gpio__PADOUTCLR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.clr = new("clr");
            this.clr.configure(this, 2, 0, "WO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : gpio__PADOUTCLR

    // Reg - gpio::INTEN
    class gpio__INTEN extends uvm_reg;
        rand uvm_reg_field en;

        function new(string name = "gpio__INTEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__INTEN

    // Reg - gpio::INTTYPE
    class gpio__INTTYPE extends uvm_reg;
        rand uvm_reg_field pin0;
        rand uvm_reg_field pin1;

        function new(string name = "gpio__INTTYPE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.pin0 = new("pin0");
            this.pin0.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
            this.pin1 = new("pin1");
            this.pin1.configure(this, 2, 2, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__INTTYPE

    // Reg - gpio::INTSTATUS
    class gpio__INTSTATUS extends uvm_reg;
        rand uvm_reg_field pin;

        function new(string name = "gpio__INTSTATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.pin = new("pin");
            this.pin.configure(this, 2, 0, "RC", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__INTSTATUS

    // Reg - gpio::PADCFG0
    class gpio__PADCFG0 extends uvm_reg;
        rand uvm_reg_field pin0;
        rand uvm_reg_field pin1;

        function new(string name = "gpio__PADCFG0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.pin0 = new("pin0");
            this.pin0.configure(this, 4, 0, "RW", 0, 'h0, 1, 1, 0);
            this.pin1 = new("pin1");
            this.pin1.configure(this, 4, 4, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__PADCFG0

    // Reg - gpio::IRQSTAT
    class gpio__IRQSTAT extends uvm_reg;
        rand uvm_reg_field gpio;

        function new(string name = "gpio__IRQSTAT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.gpio = new("gpio");
            this.gpio.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__IRQSTAT

    // Reg - gpio::IRQEN
    class gpio__IRQEN extends uvm_reg;
        rand uvm_reg_field en;

        function new(string name = "gpio__IRQEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__IRQEN

    // Reg - gpio::DMACTL
    class gpio__DMACTL extends uvm_reg;
        rand uvm_reg_field req;

        function new(string name = "gpio__DMACTL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.req = new("req");
            this.req.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio__DMACTL

    // Reg - gpio::ID
    class gpio__ID extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio__ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 0, 'h6a5d1301, 1, 1, 0);
        endfunction : build
    endclass : gpio__ID

    // Addrmap - gpio
    class gpio extends uvm_reg_block;
        rand gpio__PADDIR PADDIR;
        rand gpio__GPIOEN GPIOEN;
        rand gpio__PADIN PADIN;
        rand gpio__PADOUT PADOUT;
        rand gpio__PADOUTSET PADOUTSET;
        rand gpio__PADOUTCLR PADOUTCLR;
        rand gpio__INTEN INTEN;
        rand gpio__INTTYPE INTTYPE;
        rand gpio__INTSTATUS INTSTATUS;
        rand gpio__PADCFG0 PADCFG0;
        rand gpio__IRQSTAT IRQSTAT;
        rand gpio__IRQEN IRQEN;
        rand gpio__DMACTL DMACTL;
        rand gpio__ID ID;

        function new(string name = "gpio");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.PADDIR = new("PADDIR");
            this.PADDIR.configure(this);

            this.PADDIR.build();
            this.default_map.add_reg(this.PADDIR, 'h0);
            this.GPIOEN = new("GPIOEN");
            this.GPIOEN.configure(this);

            this.GPIOEN.build();
            this.default_map.add_reg(this.GPIOEN, 'h4);
            this.PADIN = new("PADIN");
            this.PADIN.configure(this);

            this.PADIN.build();
            this.default_map.add_reg(this.PADIN, 'h8);
            this.PADOUT = new("PADOUT");
            this.PADOUT.configure(this);

            this.PADOUT.build();
            this.default_map.add_reg(this.PADOUT, 'hc);
            this.PADOUTSET = new("PADOUTSET");
            this.PADOUTSET.configure(this);

            this.PADOUTSET.build();
            this.default_map.add_reg(this.PADOUTSET, 'h10);
            this.PADOUTCLR = new("PADOUTCLR");
            this.PADOUTCLR.configure(this);

            this.PADOUTCLR.build();
            this.default_map.add_reg(this.PADOUTCLR, 'h14);
            this.INTEN = new("INTEN");
            this.INTEN.configure(this);

            this.INTEN.build();
            this.default_map.add_reg(this.INTEN, 'h18);
            this.INTTYPE = new("INTTYPE");
            this.INTTYPE.configure(this);

            this.INTTYPE.build();
            this.default_map.add_reg(this.INTTYPE, 'h1c);
            this.INTSTATUS = new("INTSTATUS");
            this.INTSTATUS.configure(this);

            this.INTSTATUS.build();
            this.default_map.add_reg(this.INTSTATUS, 'h24);
            this.PADCFG0 = new("PADCFG0");
            this.PADCFG0.configure(this);

            this.PADCFG0.build();
            this.default_map.add_reg(this.PADCFG0, 'h28);
            this.IRQSTAT = new("IRQSTAT");
            this.IRQSTAT.configure(this);

            this.IRQSTAT.build();
            this.default_map.add_reg(this.IRQSTAT, 'hfe0);
            this.IRQEN = new("IRQEN");
            this.IRQEN.configure(this);

            this.IRQEN.build();
            this.default_map.add_reg(this.IRQEN, 'hfe4);
            this.DMACTL = new("DMACTL");
            this.DMACTL.configure(this);

            this.DMACTL.build();
            this.default_map.add_reg(this.DMACTL, 'hfe8);
            this.ID = new("ID");
            this.ID.configure(this);

            this.ID.build();
            this.default_map.add_reg(this.ID, 'hfec);
        endfunction : build
    endclass : gpio

endpackage: gpio_reg_pkg
