#!/usr/bin/env python3
"""
csr_map.py -- which CSR addresses exist on the GARUDA core and which on Spike.

A program reads every one of the 4096 CSR addresses once (csrrs t0, <addr>, x0:
a read with no write) with a trap handler that skips the instruction. An
address "exists" if its read does not trap. The program is run on the RTL
(tb_boot) and on Spike, and the two maps are compared.

    python3 tools/csr_map.py gen  sim/csr_map/csr_sweep.S
    ... build, run on tb_boot with +COMMIT, run Spike with --pmpregions=0 --triggers=0
        (GARUDA has neither); see flow/COMMANDS.md, or `make csr_map`
    python3 tools/csr_map.py diff sim/csr_map/csr_sweep.elf sim/csr_map/commit.log sim/csr_map/spike.log

Every difference is either listed in EXPECTED below, with the reason, or is
reported as unexplained and makes the exit status 1.
"""
import re
import subprocess
import sys

NAMES = {0x300: "mstatus", 0x301: "misa", 0x302: "medeleg", 0x303: "mideleg", 0x304: "mie", 0x305: "mtvec",
         0x306: "mcounteren", 0x30A: "menvcfg", 0x310: "mstatush", 0x31A: "menvcfgh", 0x320: "mcountinhibit",
         0x340: "mscratch", 0x341: "mepc", 0x342: "mcause", 0x343: "mtval", 0x344: "mip",
         0x345: "mnxti", 0x346: "mintstatus (GARUDA Rev 3.0 address)", 0x347: "mintthresh",
         0x34A: "mtinst", 0x34B: "mtval2", 0x747: "mseccfg", 0x757: "mseccfgh",
         0x7A0: "tselect", 0x7A1: "tdata1", 0x7A2: "tdata2", 0x7A3: "tdata3", 0x7A4: "tinfo", 0x7A5: "tcontrol",
         0x7A8: "mcontext", 0xB00: "mcycle", 0xB02: "minstret", 0xB80: "mcycleh", 0xB82: "minstreth",
         0xBC0: "dsu_ovf (GARUDA)", 0xC00: "cycle", 0xC01: "time", 0xC02: "instret", 0xC80: "cycleh",
         0xC81: "timeh", 0xC82: "instreth", 0xF11: "mvendorid", 0xF12: "marchid", 0xF13: "mimpid",
         0xF14: "mhartid", 0xF15: "mconfigptr", 0xFB1: "mintstatus (CLIC)"}
for i in range(3, 32):
    NAMES[0xB00 + i] = f"mhpmcounter{i}"
    NAMES[0xB80 + i] = f"mhpmcounter{i}h"
    NAMES[0x320 + i] = f"mhpmevent{i}"
    NAMES[0xC00 + i] = f"hpmcounter{i}"
    NAMES[0xC80 + i] = f"hpmcounter{i}h"
for i in range(16):
    NAMES[0x3A0 + i] = f"pmpcfg{i}"
for i in range(64):
    NAMES[0x3B0 + i] = f"pmpaddr{i}"

# Differences that are understood. Key: address; value: (which side has it, reason).
EXPECTED = {}
for a in (0x345, 0x346, 0x347, 0xFB1):
    EXPECTED[a] = ("GARUDA", "CLIC register (CORE 6.1); Spike has no CLIC")
EXPECTED[0xBC0] = ("GARUDA", "DSU overflow flag, a GARUDA custom register (CORE 6.1)")
EXPECTED[0x320] = ("Spike", "mcountinhibit is optional (privileged 1.12, 3.1.12)")
for a in (0x7A0, 0x7A1, 0x7A2, 0x7A3, 0x7A4, 0x7A8):
    EXPECTED[a] = ("Spike", "trigger registers are optional; GARUDA has no trigger module")
for a in (0xC01, 0xC81):
    EXPECTED[a] = ("Spike", "GARUDA's timer is memory mapped (block 11); a read of time traps, which the privileged spec allows")
# Open: the privileged specification the core spec cites (v1.12) says these exist,
# though each may read zero. GARUDA traps on them. Docs/BUGS.md C-16.
OPEN = "OPEN, BUGS.md C-16: privileged 1.12 says it exists (it may read 0); GARUDA traps"
for a in [0x310, 0xF15] + list(range(0x323, 0x340)) + list(range(0xB03, 0xB20)) + list(range(0xB83, 0xBA0)):
    EXPECTED[a] = ("Spike", OPEN)


def enc(addr):                       # csrrs t0, addr, x0
    return (addr << 20) | (0 << 15) | (2 << 12) | (5 << 7) | 0x73


def gen(path):
    with open(path, "w") as f:
        f.write("# csr_sweep.S - generated by tools/csr_map.py: one read of every CSR address\n"
                "    .section .text.init\n    .globl _start\n_start:\n"
                "    la   t1, handler\n    csrw mtvec, t1\n"
                "    .globl sweep\nsweep:\n")
        for a in range(4096):
            f.write(f"    .word 0x{enc(a):08x}      # csrrs t0, 0x{a:03x}, x0\n")
        f.write("    li   t2, 0x1000F000\n    li   t3, 1\n    sw   t3, 0(t2)\n1:  j    1b\n"
                "    .balign 4\nhandler:\n    csrr t1, mepc\n    addi t1, t1, 4\n    csrw mepc, t1\n    mret\n")


def sym(elf, name, nm):
    out = subprocess.run([nm, elf], stdout=subprocess.PIPE, universal_newlines=True).stdout
    for line in out.splitlines():
        p = line.split()
        if len(p) == 3 and p[2] == name:
            return int(p[0], 16)
    sys.exit(f"csr_map: no symbol {name} in {elf}")


def ranges(addrs):
    out, addrs = [], sorted(addrs)
    i = 0
    while i < len(addrs):
        j = i
        while j + 1 < len(addrs) and addrs[j + 1] == addrs[j] + 1:
            j += 1
        out.append((addrs[i], addrs[j]))
        i = j + 1
    return out


def show(lo, hi):
    name = NAMES.get(lo, "")
    if hi != lo:
        last = NAMES.get(hi, "")
        name = f"{name} .. {last}" if name and last else name
        return f"0x{lo:03x}-0x{hi:03x}  {name}"
    return f"0x{lo:03x}        {name}"


def diff(elf, rtl_log, spike_log, nm):
    base = sym(elf, "sweep", nm)
    def addr_of(epc):
        a = (epc - base) // 4
        return a if 0 <= a < 4096 and (epc - base) % 4 == 0 else None
    rtl_trap, spike_trap = set(), set()
    for line in open(rtl_log, errors="replace"):
        p = line.split()
        if p and p[0] == "TRAP" and int(p[1], 16) == 2:
            a = addr_of(int(p[2], 16))
            if a is not None:
                rtl_trap.add(a)
    exc = re.compile(r"exception trap_illegal_instruction, epc 0x([0-9a-fA-F]+)")
    for line in open(spike_log, errors="replace"):
        m = exc.search(line)
        if m:
            a = addr_of(int(m.group(1), 16))
            if a is not None:
                spike_trap.add(a)
    allv = set(range(4096))
    rtl_has, spike_has = allv - rtl_trap, allv - spike_trap
    print(f"csr_map: GARUDA has {len(rtl_has)} CSR addresses, Spike has {len(spike_has)}, "
          f"{len(rtl_has & spike_has)} in common")
    print("\nOn both:")
    for lo, hi in ranges(rtl_has & spike_has):
        print("  " + show(lo, hi))
    bad = 0
    for title, only, who in (("Only on GARUDA:", rtl_has - spike_has, "GARUDA"),
                             ("Only on Spike:", spike_has - rtl_has, "Spike")):
        print("\n" + title)
        for lo, hi in ranges(only):
            why = {EXPECTED[a][1] if a in EXPECTED and EXPECTED[a][0] == who else None for a in range(lo, hi + 1)}
            if None in why:
                bad += hi - lo + 1
                print("  " + show(lo, hi) + "    <- NOT EXPLAINED")
            else:
                print("  " + show(lo, hi) + "    (" + "; ".join(sorted(why)) + ")")
        if not only:
            print("  none")
    n_open = sum(1 for a in (rtl_has ^ spike_has) if a in EXPECTED and EXPECTED[a][1].startswith("OPEN"))
    print(f"\ncsr_map: {bad} address(es) differ with no recorded reason" if bad else
          f"\ncsr_map: every difference has a recorded reason; {n_open} of them are an open finding")
    return 1 if bad else 0


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "gen":
        gen(sys.argv[2])
    elif len(sys.argv) in (5, 6) and sys.argv[1] == "diff":
        nm = sys.argv[5] if len(sys.argv) == 6 else \
            "/home/vivado/2025.2/Vitis/gnu/riscv/linux_toolchain/lin64/bin/riscv64-amd-linux-gnu-nm"
        sys.exit(diff(sys.argv[2], sys.argv[3], sys.argv[4], nm))
    else:
        sys.exit(__doc__)
