#!/usr/bin/env python3
# =============================================================================
# garuda_gen.py -- render Design_Docs/garuda_system.yaml (GARUDA-SYS-001) into
# the headers that RTL and firmware include.
#
#   rtl/include/garuda_map.vh   Verilog-2001 `define
#   sw/common/garuda_map.h      C #define
#
# The yaml is the single source of truth for every cross-block number: address
# map, APB windows, CLIC IDs, DMA channel assignment, boot vector. Nothing in
# either output file is hand-edited - rerun this script instead:
#
#   python3 tools/garuda_gen.py            # write both headers
#   python3 tools/garuda_gen.py --check    # exit 1 if either is stale (CI)
# =============================================================================
import argparse
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
YAML = os.path.join(ROOT, "Design_Docs", "garuda_system.yaml")
OUT_VH = os.path.join(ROOT, "rtl", "include", "garuda_map.vh")
OUT_H = os.path.join(ROOT, "sw", "common", "garuda_map.h")


def ident(s):
    return re.sub(r"[^A-Za-z0-9]+", "_", str(s)).strip("_").upper()


def id_range(v):
    """clic map ids are ints or 'a..b' strings."""
    if isinstance(v, int):
        return [v]
    a, b = str(v).split("..")
    return list(range(int(a), int(b) + 1))


def collect(sysdef):
    """Return an ordered list of (section, name, value, comment)."""
    out = []
    meta = sysdef["meta"]
    out.append(("Identity", "SYS_REVISION", '"%s"' % meta["revision"], meta["doc_id"]))

    clk = sysdef["clocks"]
    out.append(("Clocks", "REFCLK_MHZ", int(clk["refclk"]["freq_mhz"]), "external reference"))
    out.append(("Clocks", "HCLK_MHZ", int(clk["hclk"]["freq_mhz"]), "refclk / DIV (default)"))
    out.append(("Clocks", "HCLK_DIV_DEFAULT", clk["hclk"]["div_default"], "divider encoding is 2/4/8/16"))
    out.append(("Clocks", "PCLK_MHZ", int(clk["pclk"]["freq_mhz"]), "hclk / 2, toggle flop"))

    rst = sysdef["reset"]
    out.append(("Reset", "RESET_STRETCH_CYCLES", rst["stretch"]["cycles"], "refclk cycles"))

    for r in sysdef["address_map"]["regions"]:
        n = ident(r["name"])
        out.append(("Address map", n + "_BASE", r["base"], None))
        out.append(("Address map", n + "_SIZE", r["size_kib"] * 1024, "%d KiB" % r["size_kib"]))

    apb = sysdef["apb"]
    out.append(("APB", "APB_WINDOW_BYTES", apb["window_size_kib"] * 1024, None))
    out.append(("APB", "APB_TIMEOUT_PCLK", apb["timeout_cycles"], "PREADY timeout"))
    mask = 0
    for w in apb["windows"]:
        n = ident(w["name"])
        # Window index == haddr[15:12] == PSEL bit. The yaml's base field is
        # authoritative (DECISIONS: APB-0); the index is cross-checked.
        idx = (w["base"] >> 12) & 0xF
        if idx != w["index"]:
            sys.exit("apb window %s: index %d != base-derived %d" % (n, w["index"], idx))
        out.append(("APB", "APB_WIN_" + n, idx, "0x%08X, block %d" % (w["base"], w["block"])))
        out.append(("APB", "APB_BASE_" + n, w["base"], None))
        mask |= 1 << idx
    out.append(("APB", "APB_WINDOW_MASK_ALL", mask, "every window the map defines"))

    for e in sysdef["clic"]["map"]:
        src = ident(e["source"])
        ids = id_range(e["id"])
        if src.startswith("RESERVED"):
            continue
        if len(ids) == 1:
            out.append(("CLIC IDs", "CLIC_ID_" + src, ids[0], None))
        else:
            out.append(("CLIC IDs", "CLIC_ID_" + src + "_FIRST", ids[0], "%d..%d" % (ids[0], ids[-1])))
    out.append(("CLIC IDs", "CLIC_NUM_IDS", sysdef["clic"]["id_width"], None))

    dma = sysdef["dma"]
    out.append(("DMA", "DMA_CHANNELS", dma["channels"], None))
    for a in dma["assignment"]:
        out.append(("DMA", "DMA_PRIO_CH%d" % a["ch"], a["priority"], a["peripheral"]))
    for a in dma["assignment"]:
        if a["peripheral"] != "reserved":
            out.append(("DMA", "DMA_CH_" + ident(a["peripheral"]), a["ch"], a["function"]))

    boot = sysdef["boot"]
    out.append(("Boot", "RESET_VECTOR", boot["reset_vector"], None))
    return out


def fmt_val(name, v, c_style):
    if isinstance(v, str):
        return v
    if re.search(r"(BASE|SIZE|VECTOR|MASK|BYTES)", name):
        return ("0x%08X" % v) if c_style else ("32'h%04X_%04X" % (v >> 16, v & 0xFFFF))
    return str(v)


def render(items, c_style):
    src = os.path.relpath(YAML, ROOT)
    lines = []
    if c_style:
        lines += ["/* GENERATED by tools/garuda_gen.py from %s - DO NOT EDIT */" % src,
                  "#ifndef GARUDA_MAP_H", "#define GARUDA_MAP_H", ""]
    else:
        lines += ["// GENERATED by tools/garuda_gen.py from %s - DO NOT EDIT" % src,
                  "`ifndef GARUDA_MAP_VH", "`define GARUDA_MAP_VH", ""]
    section = None
    for sec, name, val, cmt in items:
        if sec != section:
            lines.append(("/* ---- %s ---- */" if c_style else "// ---- %s ----") % sec)
            section = sec
        v = fmt_val(name, val, c_style)
        tail = ""
        if cmt:
            tail = ("  /* %s */" % cmt) if c_style else ("  // %s" % cmt)
        if c_style:
            lines.append("#define GARUDA_%-28s %s%s" % (name, v, tail))
        else:
            lines.append("`define GARUDA_%-28s %s%s" % (name, v, tail))
    lines += ["", "#endif" if c_style else "`endif", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = ap.parse_args()
    with open(YAML) as f:
        sysdef = yaml.safe_load(f)
    items = collect(sysdef)
    outs = {OUT_VH: render(items, False), OUT_H: render(items, True)}
    stale = False
    for path, text in outs.items():
        cur = open(path).read() if os.path.exists(path) else None
        if cur == text:
            continue
        if args.check:
            print("STALE: %s" % os.path.relpath(path, ROOT))
            stale = True
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(text)
            print("wrote %s" % os.path.relpath(path, ROOT))
    sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
