#!/usr/bin/env python3
# =============================================================================
# vendor_sync.py -- provenance for the third-party RTL under rtl/third_party/
#
# Every vendored file is recorded in rtl/third_party/MANIFEST.yaml with the
# upstream URL, the exact commit it came from, its SPDX licence and a sha256 of
# the file as vendored. Three commands:
#
#   python3 tools/vendor_sync.py --check    exit 1 if any vendored file differs
#                                           from its recorded hash (CI / review)
#   python3 tools/vendor_sync.py --update   re-hash after a deliberate re-vendor
#   python3 tools/vendor_sync.py --report   print the table for THIRD_PARTY_NOTICES
#
# MANIFEST.yaml is hand-written provenance (url, commit, licence, why we use it).
# HASHES.txt is generated: "<sha256>  <repo-relative path>", sha256sum format,
# so `sha256sum -c rtl/third_party/HASHES.txt` works without this script too.
#
# Why: a silent local edit to upstream code is how a tapeout loses track of what
# it is shipping. Policy (Docs/DECISIONS.md D-22) is that upstream files are
# never edited - deltas live in our wrappers, and the rare unavoidable change
# goes in <ip>/patches/*.patch, which this script applies and records.
# =============================================================================
import argparse
import hashlib
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TP = os.path.join(ROOT, "rtl", "third_party")
MANIFEST = os.path.join(TP, "MANIFEST.yaml")
HASHES = os.path.join(TP, "HASHES.txt")


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def walk_sources(ip_dir):
    """Every vendored source file of one IP, repo-relative, sorted."""
    src = os.path.join(TP, ip_dir, "src")
    out = []
    for dirpath, _, names in os.walk(src):
        for n in sorted(names):
            p = os.path.join(dirpath, n)
            out.append(os.path.relpath(p, ROOT))
    return sorted(out)


def load():
    with open(MANIFEST) as f:
        return yaml.safe_load(f)


def read_hashes():
    if not os.path.exists(HASHES):
        return {}
    out = {}
    for line in open(HASHES):
        line = line.strip()
        if line and not line.startswith("#"):
            h, p = line.split(None, 1)
            out[p.strip()] = h
    return out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--update", action="store_true")
    g.add_argument("--report", action="store_true")
    args = ap.parse_args()

    man = load()
    recorded = read_hashes()
    found = []
    for ip in man["ips"]:
        found += walk_sources(ip["dir"])

    if args.update:
        with open(HASHES, "w") as f:
            f.write("# GENERATED by tools/vendor_sync.py --update - sha256sum format\n")
            f.write("# Provenance (url, commit, licence) is in MANIFEST.yaml.\n")
            for p in found:
                f.write("%s  %s\n" % (sha256(os.path.join(ROOT, p)), p))
        print("HASHES.txt: %d files" % len(found))
        return 0

    if args.report:
        print("| IP | Upstream | Commit | Licence | Files |")
        print("|---|---|---|---|---|")
        for ip in man["ips"]:
            n = len(walk_sources(ip["dir"]))
            print("| `%s` | %s | `%s` | %s | %d |" %
                  (ip["name"], ip["upstream"], ip["commit"][:12], ip["spdx"], n))
        return 0

    bad = missing = 0
    for p in found:
        if p not in recorded:
            print("UNRECORDED: %s (vendored but not hashed)" % p)
            missing += 1
        elif sha256(os.path.join(ROOT, p)) != recorded[p]:
            print("MODIFIED: %s" % p)
            print("   upstream files are never edited - put the delta in a wrapper,")
            print("   or in <ip>/patches/ with a Docs/BUGS.md entry (D-22)")
            bad += 1
    for p in recorded:
        if not os.path.exists(os.path.join(ROOT, p)):
            print("MISSING: %s" % p)
            missing += 1

    if bad or missing:
        print("\nvendor_sync: %d modified, %d missing/unrecorded" % (bad, missing))
        return 1
    print("vendor_sync: %d files across %d IPs match HASHES.txt" % (len(found), len(man["ips"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
