
// This file was autogenerated by PeakRDL-uvm
package timers_reg_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - timers::MTIME_LO
    class timers__MTIME_LO extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__MTIME_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : timers__MTIME_LO

    // Reg - timers::MTIME_HI
    class timers__MTIME_HI extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__MTIME_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : timers__MTIME_HI

    // Reg - timers::MTIMECMP_LO
    class timers__MTIMECMP_LO extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__MTIMECMP_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 0, 'hffffffff, 1, 1, 0);
        endfunction : build
    endclass : timers__MTIMECMP_LO

    // Reg - timers::MTIMECMP_HI
    class timers__MTIMECMP_HI extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__MTIMECMP_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 0, 'hffffffff, 1, 1, 0);
        endfunction : build
    endclass : timers__MTIMECMP_HI

    // Reg - timers::WDTCTL
    class timers__WDTCTL extends uvm_reg;
        rand uvm_reg_field en;
        rand uvm_reg_field warnen;
        rand uvm_reg_field rsvd;

        function new(string name = "timers__WDTCTL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            this.warnen = new("warnen");
            this.warnen.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 30, 2, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : timers__WDTCTL

    // Reg - timers::WDTLOAD
    class timers__WDTLOAD extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__WDTLOAD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 0, 'hffffffff, 1, 1, 0);
        endfunction : build
    endclass : timers__WDTLOAD

    // Reg - timers::WDTVAL
    class timers__WDTVAL extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__WDTVAL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : timers__WDTVAL

    // Reg - timers::WDTKICK
    class timers__WDTKICK extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__WDTKICK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : timers__WDTKICK

    // Reg - timers::WDTWARN
    class timers__WDTWARN extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "timers__WDTWARN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : timers__WDTWARN

    // Addrmap - timers
    class timers extends uvm_reg_block;
        rand timers__MTIME_LO MTIME_LO;
        rand timers__MTIME_HI MTIME_HI;
        rand timers__MTIMECMP_LO MTIMECMP_LO;
        rand timers__MTIMECMP_HI MTIMECMP_HI;
        rand timers__WDTCTL WDTCTL;
        rand timers__WDTLOAD WDTLOAD;
        rand timers__WDTVAL WDTVAL;
        rand timers__WDTKICK WDTKICK;
        rand timers__WDTWARN WDTWARN;

        function new(string name = "timers");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.MTIME_LO = new("MTIME_LO");
            this.MTIME_LO.configure(this);

            this.MTIME_LO.build();
            this.default_map.add_reg(this.MTIME_LO, 'h0);
            this.MTIME_HI = new("MTIME_HI");
            this.MTIME_HI.configure(this);

            this.MTIME_HI.build();
            this.default_map.add_reg(this.MTIME_HI, 'h4);
            this.MTIMECMP_LO = new("MTIMECMP_LO");
            this.MTIMECMP_LO.configure(this);

            this.MTIMECMP_LO.build();
            this.default_map.add_reg(this.MTIMECMP_LO, 'h8);
            this.MTIMECMP_HI = new("MTIMECMP_HI");
            this.MTIMECMP_HI.configure(this);

            this.MTIMECMP_HI.build();
            this.default_map.add_reg(this.MTIMECMP_HI, 'hc);
            this.WDTCTL = new("WDTCTL");
            this.WDTCTL.configure(this);

            this.WDTCTL.build();
            this.default_map.add_reg(this.WDTCTL, 'h10);
            this.WDTLOAD = new("WDTLOAD");
            this.WDTLOAD.configure(this);

            this.WDTLOAD.build();
            this.default_map.add_reg(this.WDTLOAD, 'h14);
            this.WDTVAL = new("WDTVAL");
            this.WDTVAL.configure(this);

            this.WDTVAL.build();
            this.default_map.add_reg(this.WDTVAL, 'h18);
            this.WDTKICK = new("WDTKICK");
            this.WDTKICK.configure(this);

            this.WDTKICK.build();
            this.default_map.add_reg(this.WDTKICK, 'h1c);
            this.WDTWARN = new("WDTWARN");
            this.WDTWARN.configure(this);

            this.WDTWARN.build();
            this.default_map.add_reg(this.WDTWARN, 'h20);
        endfunction : build
    endclass : timers

endpackage: timers_reg_pkg
